import { createEnv } from "@t3-oss/env-nextjs";
import { string } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: string().url(),
    OPENAI_API_KEY: string(),
    QSTASH_TOKEN: string(),
    QSTASH_CURRENT_SIGNING_KEY: string(),
    QSTASH_NEXT_SIGNING_KEY: string(),
    PUSHER_SECRET: string(),
    CLERK_SECRET_KEY: string(),
  },
  client: {
    NEXT_PUBLIC_PUSHER_KEY: string(),
    NEXT_PUBLIC_PUSHER_ID: string(),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string(),
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: string(),
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: string(),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: string(),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: string(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NEXT_PUBLIC_PUSHER_ID: process.env.NEXT_PUBLIC_PUSHER_ID,
    NEXT_PUBLIC_PUSHER_KEY: process.env.NEXT_PUBLIC_PUSHER_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    PUSHER_SECRET: process.env.PUSHER_SECRET,
    QSTASH_CURRENT_SIGNING_KEY: process.env.QSTASH_CURRENT_SIGNING_KEY,
    QSTASH_NEXT_SIGNING_KEY: process.env.QSTASH_NEXT_SIGNING_KEY,
    QSTASH_TOKEN: process.env.QSTASH_TOKEN,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL:
      process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL:
      process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
  },
});
