import { cx } from "cva";
import Providers from "./Providers";
import "./globals.css";
import { Atkinson_Hyperlegible } from "next/font/google";
import Header from "./Header";

const ak = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx(ak.className, "text-slate-50 bg-slate-950")}>
        <Providers>
          <Header />

          {children}
        </Providers>
      </body>
    </html>
  );
}
